import icon1 from "../assets/team flame 1.svg.svg";
import icon2 from "../assets/team flame 2.svg.svg";
import icon3 from "../assets/team flame 3.svg.svg";
import icon4 from "../assets/team flame 4.svg.svg";
import icon5 from "../assets/team flame 5.svg.svg";
import icon6 from "../assets/team flame 6.svg.svg";
import icon7 from "../assets/team flame 7.svg.svg";
// =================EMPLOYEES IMAGES======================================
// import image1 from "../src/assets/image1.svg";
// import image2 from "../src/assets/image2.svg";
// import image3 from "../src/assets/image3.svg";
// import image4 from "../src/assets/image4.svg";
// import image5 from "../src/assets/image5.svg";

export const table = [
  {
    id: 1,
    title: "Website Project Update On Slack",
    icon: icon1,
    start: "Start: 03 Mar 2023",
    end: "End: 10 Mar 2023",
    action: "Planned",
  },
  {
    id: 2,
    title: "Productize Beta Testing",
    icon: icon2,
    start: "Start: 03 Mar 2023",
    end: "End: 10 Mar 2023",
    action: "Completed",
  },
  {
    id: 3,
    title: "Website Project Update On Slack",
    icon: icon3,
    start: "Start: 03 Mar 2023",
    end: "End: 10 Mar 2023",
    action: "In Progress",
  },
  {
    id: 4,
    title: "Website Project Update On Slack",
    icon: icon4,
    start: "Start: 03 Mar 2023",
    end: "End: 10 Mar 2023",
    action: "Planned",
  },
  {
    id: 5,
    title: "Productize Beta Testing",
    icon: icon5,
    start: "Start: 03 Mar 2023",
    end: "End: 10 Mar 2023",
    action: "Completed",
  },
  {
    id: 6,
    title: "Website Project Update On Slack",
    icon: icon6,
    start: "Start: 03 Mar 2023",
    end: "End: 10 Mar 2023",
    action: "In Progress",
  },
  {
    id: 7,
    title: "Website Project Update On Slack",
    icon: icon7,
    start: "Start: 03 Mar 2023",
    end: "End: 10 Mar 2023",
    action: "Planned",
  },
];
// export const leave = [
//   {
//     id: 1,
//     title: "Website Project Update On Slack",
//     icon: icon1,
//     start: "Start: 03 Mar 2023",
//     end: "End: 10 Mar 2023",
//     action: "Pending",
//     days: "6 Days",
//     leave: "Casual Leave",
//   },
//   {
//     id: 2,
//     title: "Productize Beta Testing",
//     icon: icon2,
//     start: "Start: 03 Mar 2023",
//     end: "End: 10 Mar 2023",
//     action: "Pending",
//     days: "6 Days",
//     leave: "Sick Leave",
//   },
//   {
//     id: 3,
//     title: "Website Project Update On Slack",
//     icon: icon3,
//     start: "Start: 03 Mar 2023",
//     end: "End: 10 Mar 2023",
//     action: "Pending",
//     days: "6 Days",
//     leave: "Annual Leave",
//   },
//   {
//     id: 4,
//     title: "Website Project Update On Slack",
//     icon: icon4,
//     start: "Start: 03 Mar 2023",
//     end: "End: 10 Mar 2023",
//     action: "Declined",
//     days: "6 Days",
//     leave: "Annual Leave",
//   },
//   {
//     id: 5,
//     title: "Productize Beta Testing",
//     icon: icon5,
//     start: "Start: 03 Mar 2023",
//     end: "End: 10 Mar 2023",
//     action: "Approved",
//     days: "6 Days",
//     leave: "Sick Leave",
//   },
//   {
//     id: 6,
//     title: "Website Project Update On Slack",
//     icon: icon6,
//     start: "Start: 03 Mar 2023",
//     end: "End: 10 Mar 2023",
//     action: "Pending",
//     days: "6 Days",
//     leave: "Annual Leave",
//   },
//   {
//     id: 7,
//     title: "Website Project Update On Slack",
//     icon: icon7,
//     start: "Start: 03 Mar 2023",
//     end: "End: 10 Mar 2023",
//     action: "Declined",
//     days: "6 Days",
//     leave: "Annual Leave",
//   },
//   {
//     id: 8,
//     title: "Website Project Update On Slack",
//     icon: icon7,
//     start: "Start: 03 Mar 2023",
//     end: "End: 10 Mar 2023",
//     action: "Approved",
//     days: "6 Days",
//     leave: "Casual Leave",
//   },
//   {
//     id: 9,
//     title: "Website Project Update On Slack",
//     icon: icon7,
//     start: "Start: 03 Mar 2023",
//     end: "End: 10 Mar 2023",
//     action: "Approved",
//     days: "6 Days",
//     leave: "Casual Leave",
//   },
//   {
//     id: 10,
//     title: "Website Project Update On Slack",
//     icon: icon7,
//     start: "Start: 03 Mar 2023",
//     end: "End: 10 Mar 2023",
//     action: "Declined",
//     days: "6 Days",
//     leave: "Sick Leave",
//   },
// ];

// export const Employ = [
//   {
//     id: 1,
//     img: image1,
//     names: "Oluwatosin Sanya",
//     email: "tosinsanya@tmt.com",
//     team: "Adminstration",
//     supervisor: "Eric Ten-Hagg",
//     status: "Hybrid",
//     role: "Product Designer",
//   },
//   {
//     id: 2,
//     img: image2,
//     names: "Raheem Sterling",
//     email: "raheem@tmt.com",
//     team: "Product",
//     supervisor: "Joshua Zirkzee",
//     status: "Remote",
//     role: "Web Developer",
//   },
//   {
//     id: 3,
//     img: image3,
//     names: "Eggy James",
//     email: "eggys767@tmt.com",
//     team: "Adminstration",
//     supervisor: "Bukayo Saka",
//     status: "On-Site",
//     role: "Data Analyst",
//   },
//   {
//     id: 4,
//     img: image4,
//     names: "Chukwudi Tobiloba",
//     email: "chtobiloba@tmt.com",
//     team: "Marketing",
//     supervisor: "Eric Ten-Hagg",
//     status: "On-Site",
//     role: "Cyber Analyst",
//   },
//   {
//     id: 5,
//     img: image5,
//     names: "Olawole Anita",
//     email: "olawo999@tmt.com",
//     team: "Product",
//     supervisor: "Eric Ten-Hagg",
//     status: "Remote",
//     role: "Web Developer",
//   },
//   {
//     id: 6,
//     img: image1,
//     names: "Oluwatosin Sanya",
//     email: "tosinsanya@tmt.com",
//     team: "Adminstration",
//     supervisor: "Eric Ten-Hagg",
//     status: "Hybrid",
//     role: "Data Analyst",
//   },
//   {
//     id: 7,
//     img: image2,
//     names: "Raheem Sterling",
//     email: "raheem@tmt.com",
//     team: "Product",
//     supervisor: "Bukayo Saka",
//     status: "Remote",
//     role: "Product Designer",
//   },
//   {
//     id: 8,
//     img: image3,
//     names: "Eggy James",
//     email: "eggys767@tmt.com",
//     team: "Adminstration",
//     supervisor: "Eric Ten-Hagg",
//     status: "On-Site",
//     role: "Cyber Analyst",
//   },
//   {
//     id: 9,
//     img: image4,
//     names: "Raheem Sterling",
//     email: "raheem@tmt.com",
//     team: "Product",
//     supervisor: "Eric Ten-Hagg",
//     status: "Remote",
//     role: "Web Developer",
//   },
//   {
//     id: 10,
//     img: image5,
//     names: "Chukwudi Tobiloba",
//     email: "chtobiloba@tmt.com",
//     team: "Marketing",
//     supervisor: "Bukayo Saka",
//     status: "On-Site",
//     role: "Data Analyst",
//   },
// ];

export const payroll = [
  {
    id: 1,
    salary: "N560,000",
    allowance: "N50,000",
    deductions: "N15,000",
    tak: "5%",
    netSalary: "N560,000",
  },
  {
    id: 2,
    salary: "N560,000",
    allowance: "N50,000",
    deductions: "N15,000",
    tak: "5%",
    netSalary: "N560,000",
  },
  {
    id: 3,
    salary: "N560,000",
    allowance: "N50,000",
    deductions: "N15,000",
    tak: "5%",
    netSalary: "N560,000",
  },
  {
    id: 4,
    salary: "N560,000",
    allowance: "N50,000",
    deductions: "N15,000",
    tak: "5%",
    netSalary: "N560,000",
  },
  {
    id: 5,
    salary: "N560,000",
    allowance: "N50,000",
    deductions: "N15,000",
    tak: "5%",
    netSalary: "N560,000",
  },
  {
    id: 6,
    salary: "N560,000",
    allowance: "N50,000",
    deductions: "N15,000",
    tak: "5%",
    netSalary: "N560,000",
  },
  {
    id: 7,
    salary: "N560,000",
    allowance: "N50,000",
    deductions: "N15,000",
    tak: "5%",
    netSalary: "N560,000",
  },
  {
    id: 8,
    salary: "N560,000",
    allowance: "N50,000",
    deductions: "N15,000",
    tak: "5%",
    netSalary: "N560,000",
},
];